// This file is auto-generated by the i18n-keys-generator script.
// Do not edit this file directly.

import en from '@/locales/en.json';

type NestedKey<T> = T extends object ? { [K in keyof T]: `${K & string}` | `${K & string}.${NestedKey<T[K]>}` }[keyof T] : never;
export type TranslationKey = NestedKey<typeof en>;
